# Generated by Django 4.1.1 on 2022-11-01 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_auctionlistings_category_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlistings',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
