# Generated by Django 4.1.1 on 2022-10-13 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_auctionlistings_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlistings',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='commment',
        ),
        migrations.AddField(
            model_name='comments',
            name='auction_listings',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='auctions.auctionlistings'),
        ),
        migrations.AddField(
            model_name='comments',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
