# Generated by Django 4.1.1 on 2022-10-13 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_remove_auctionlistings_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='auction_listings',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='auctions.auctionlistings'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='auction_listings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.auctionlistings'),
        ),
    ]
