# Generated by Django 4.1.1 on 2022-10-14 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_bids_auction_listings_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlistings',
            old_name='initial_bid',
            new_name='bid',
        ),
        migrations.AlterField(
            model_name='auctionlistings',
            name='category',
            field=models.CharField(blank=True, choices=[('1', 'Eletronic'), ('2', 'Toys'), ('3', 'Fashion'), ('4', 'Home'), ('5', 'Food')], max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='bids',
            name='auction_listings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.auctionlistings'),
        ),
    ]
