# Generated by Django 4.1.1 on 2022-10-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_auctionlistings_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlistings',
            name='category',
            field=models.CharField(blank=True, choices=[('Tech', 'Eletronic'), ('Toys', 'Toys'), ('Fashion', 'Fashion'), ('Home', 'Home'), ('Food', 'Food')], max_length=24, null=True),
        ),
    ]
